import 'package:fitness_flutter/core/const/path_constants.dart';
import 'package:fitness_flutter/core/const/text_constants.dart';
import 'package:fitness_flutter/data/exercise_data.dart';
import 'package:fitness_flutter/data/workout_data.dart';
import 'package:fitness_flutter/screens/onboarding/widget/onboarding_tile.dart';

class DataConstants {
  // Onboarding
  static final onboardingTiles = [
    OnboardingTile(
      title: TextConstants.onboarding1Title,
      mainText: TextConstants.onboarding1Description,
      imagePath: PathConstants.onboarding1,
    ),
    OnboardingTile(
      title: TextConstants.onboarding2Title,
      mainText: TextConstants.onboarding2Description,
      imagePath: PathConstants.onboarding2,
    ),
    OnboardingTile(
      title: TextConstants.onboarding3Title,
      mainText: TextConstants.onboarding3Description,
      imagePath: PathConstants.onboarding3,
    ),
  ];

  // Workouts
  static final List<WorkoutData> workouts = [
    WorkoutData(
        title: TextConstants.yogaTitle,
        exercices: TextConstants.yogaExercises,
        minutes: TextConstants.yogaMinutes,
        currentProgress: 10,
        progress: 16,
        image: PathConstants.yoga,
        exerciseDataList: [
          ExerciseData(
            title: 'Bench Press',
            minutes: TextConstants.recliningMinutes,
            progress: 0.5,
            imagePath: ['assets/images/exercises/workouts/bench-press.jpg',],
            name: [],
            amount: [],
            video: PathConstants.videoVideo,
            description: 'The bench press is a fundamental compound exercise targeting the pectoralis major, triceps, and anterior deltoids. Lying on a flat bench, you press a barbell upwards from your chest. It\'s essential for building chest strength and size, making it a staple in most strength training routines.',
            steps: [
              'Lie flat on a bench with your eyes directly under the barbell. Plant your feet firmly on the ground, about shoulder-width apart, ensuring your back maintains a natural arch.',
              'Grip the barbell with hands slightly wider than shoulder-width apart, ensuring your wrists are straight and aligned with your forearms.',
              'Lift the bar off the rack by straightening your arms and moving it into position directly above your chest.',
              'Lower the barbell slowly and under control to your mid-chest, keeping your elbows at about a 75-degree angle from your body. Maintain a steady, controlled pace, taking about 2-3 seconds to lower the bar.',
              'Push the barbell back up to the starting position, driving through your chest and extending your arms fully. Keep the bar path vertical and exhale as you push up. Ensure your shoulder blades remain retracted and your back maintains its natural arch.'
            ],
          ),
          ExerciseData(
            title: 'Push-Ups',
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.3,
            imagePath: ['assets/images/exercises/workouts/push-ups.jpg',],
            name: [],
            amount: [],
            video: PathConstants.cowPoseVideo,
            description: 'Push-ups are a bodyweight exercise that targets the chest, triceps, and shoulders. Starting in a plank position, you lower your body until your chest nearly touches the floor, then push back up. They are excellent for building upper body strength and core stability, and can be done anywhere without equipment.',
            steps: [
              'Begin in a high plank position with your hands placed slightly wider than shoulder-width apart, fingers pointing forward. Your body should form a straight line from your head to your heels.',
              'Lower your body by bending your elbows, keeping them at about a 45-degree angle to your torso. Lower until your chest nearly touches the floor, ensuring your body stays in a straight line throughout the movement. Engage your core to prevent your hips from sagging or piking.',
              'Push your body back up to the starting position by straightening your arms, ensuring your elbows are not locked out at the top. Exhale as you push up and maintain a steady pace. Keep your neck neutral by looking at a spot on the floor about six inches in front of your hands.'
            ],
          ),
          ExerciseData(
            title: 'Incline Press',
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.99,
            imagePath: ['assets/images/exercises/workouts/incline-dumbbell-bench-press.jpg'],
            name: [],
            amount: [],
            video: PathConstants.warriorIIVideo,
            description: 'The incline dumbbell press targets the upper chest, triceps, and shoulders. Performed on a bench set to a 30-45 degree incline, you press dumbbells upwards from your chest. This exercise enhances upper chest development and promotes balanced muscle growth.',
            steps: [
              'Adjust an adjustable bench to a 30-45 degree incline. Sit on the bench and rest a dumbbell on each thigh.',
              'Lie back on the bench, bringing the dumbbells to your shoulders. Your palms should face forward and your elbows should be bent at about a 90-degree angle.',
              'Position the dumbbells just outside your chest, with your elbows directly under your wrists.',
              'Press the dumbbells up and together by extending your arms until they are fully extended above your chest. Your arms should form a slight arc, and the dumbbells should not touch at the top.',
              'Lower the dumbbells slowly and under control back to the starting position, taking about 2-3 seconds. Ensure your elbows drop slightly below your shoulders to get a full stretch in your chest.',
              'Inhale as you lower the dumbbells and exhale as you press them back up. Keep your core engaged to maintain stability and support your lower back.'
            ],
          ),
        ]),
    WorkoutData(
        title: TextConstants.pilatesTitle,
        exercices: TextConstants.pilatesExercises,
        minutes: TextConstants.pilatesMinutes,
        currentProgress: 1,
        progress: 20,
        image: 'assets/images/exercises/workouts/legs.jpg',
        exerciseDataList: [
          ExerciseData(
            title: 'Squats',
            minutes: TextConstants.recliningMinutes,
            progress: 0.1,
            imagePath: ['assets/images/exercises/workouts/squat-800.jpg'],
            name: [],
            amount: [],
            video: PathConstants.recliningVideo,
            description: 'Squats are a foundational compound exercise targeting the quadriceps, hamstrings, glutes, and lower back. Standing with feet shoulder-width apart, you lower your hips back and down as if sitting in a chair, then return to standing. Squats are essential for building overall leg strength and muscle mass.',
            steps: [
              'Stand with your feet shoulder-width apart and your toes slightly pointed outwards. Position a barbell across your upper back, gripping it with your hands just outside shoulder-width.',
              'Brace your core and begin the movement by pushing your hips back and bending your knees. Keep your chest up and your back straight.',
              'Lower yourself until your thighs are at least parallel to the ground or as deep as your flexibility allows.',
              'Push through your heels to return to the standing position, extending your hips and knees. Ensure your knees track over your toes and avoid letting them cave inwards.',
              'Inhale as you lower down and exhale as you push up.',
            ],
          ),
          ExerciseData(
            title: 'Lunges',
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.1,
            imagePath: ['assets/images/exercises/workouts/dumbbell-lunge-800.jpg'],
            name: [],
            amount: [],
            video: PathConstants.cowPoseVideo,
            description: 'Lunges work the quadriceps, hamstrings, glutes, and calves. From a standing position, step forward with one leg and lower your hips until both knees are at 90-degree angles, then push back up to the starting position. They are excellent for improving balance and unilateral leg strength.',
            steps: [
              'Stand tall with your feet hip-width apart. Place your hands on your hips or hold dumbbells by your sides.',
              'Take a big step forward with your right leg, keeping your torso upright.',
              'Take a big step forward with your right leg, keeping your torso upright.',
              'Push through your right heel to return to the starting position.',
              'Alternate legs and repeat for the desired number of reps. Inhale as you step forward and lower, exhale as you push back up.',
            ],
          ),
          ExerciseData(
            title: 'Leg Press',
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.0,
            imagePath: ['assets/images/exercises/workouts/sled-leg-press-800.jpg'],
            name: [],
            amount: [],
            video: PathConstants.warriorIIVideo,
            description: 'The leg press machine targets the quadriceps, hamstrings, and glutes. Sitting in the machine, you press a weighted platform away from your body by extending your legs, then slowly bring it back. This exercise is great for building leg strength with controlled movement and support.',
            steps: [
              'Sit in the leg press machine with your back and head pressed firmly against the back support. Place your feet on the platform shoulder-width apart.',
              'Grip the handles and release the safety bars.',
              'Lower the platform by bending your knees to a 90-degree angle, keeping your feet flat and your knees in line with your toes.',
              'Push the platform back up by extending your legs fully without locking your knees.',
              'Inhale as you lower the platform and exhale as you press it back up.',
            ],
          ),
          ExerciseData(
            title: 'Deadlift',
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.0,
            imagePath: ['assets/images/exercises/workouts/deadlift.jpg'],
            name: [],
            amount: [],
            video: PathConstants.warriorIIVideo,
            description: 'Deadlifts are a powerful compound exercise that targets the entire posterior chain, including the hamstrings, glutes, lower back, and core. Standing with feet hip-width apart, you lift a barbell from the ground to hip level by extending your hips and knees, then lower it back down. Deadlifts are essential for building overall strength and muscle mass.',
            steps: [
              'Stand with your feet hip-width apart with the barbell over your mid-foot. Bend at the hips and knees to grip the barbell with hands shoulder-width apart.',
              'With a neutral spine, brace your core and lift the bar by extending your hips and knees simultaneously. Keep the bar close to your body.',
              'Stand tall at the top of the lift with your hips and knees fully extended, shoulders back.',
              'Lower the bar back to the ground by pushing your hips back first, then bending your knees once the bar passes them.',
              'Inhale before you lift, hold your breath as you lift, and exhale at the top or after lowering the bar.',
            ],
          ),
        ]),
    WorkoutData(
        title: TextConstants.fullBodyTitle,
        exercices: TextConstants.fullBodyExercises,
        minutes: TextConstants.fullBodyMinutes,
        currentProgress: 12,
        progress: 14,
        image: 'assets/images/exercises/workouts/backi.jpg',
        exerciseDataList: [
          ExerciseData(
            imagePath: ['assets/images/exercises/workouts/pull-ups-800.jpg'],
            name: [],
            amount: [],
            title: 'Pull-Ups',
            minutes: TextConstants.recliningMinutes,
            progress: 0.99,
            video: PathConstants.recliningVideo,
            description: 'Pull-ups are a fundamental bodyweight exercise targeting the latissimus dorsi, biceps, and upper back. Performing them involves hanging from a bar and pulling your body up until your chin is above the bar. This exercise is excellent for developing upper body strength and width.',
            steps: [
              'Grab the pull-up bar with palms facing away from you (overhand grip) and hands shoulder-width apart.',
              'Hang with your arms fully extended and your legs crossed behind you to keep your body stable.',
              'Engage your lats and pull your body upward until your chin is above the bar. Focus on driving your elbows down and back.',
              'Lower yourself back down in a controlled manner until your arms are fully extended.',
              'Exhale as you pull up and inhale as you lower down.',
            ],
          ),
          ExerciseData(
            title: 'Lat Pulldown',
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.6,
            imagePath: ['assets/images/exercises/workouts/lat-pulldown-800.jpg'],
            name: [],
            amount: [],
            video: PathConstants.cowPoseVideo,
            description: 'Lat pulldowns are performed on a cable machine and target the latissimus dorsi, helping to build a wider back. You pull a bar down towards your chest while seated, simulating a pull-up motion.',
            steps: [
              'Sit at a lat pulldown machine and adjust the thigh pad to secure your legs. Grab the bar with a wide overhand grip.',
              'Lean back slightly and pull the bar down towards your upper chest, driving your elbows down and back.',
              'Hold the contraction for a moment, squeezing your lats.',
              'Slowly return the bar to the starting position, fully extending your arms.',
              'Exhale as you pull the bar down and inhale as you return it.',
            ],
          ),
        ]),
    WorkoutData(
      title: TextConstants.armsTitle,
      exercices: TextConstants.armsExercises,
      minutes: TextConstants.armsMinutes,
      currentProgress: 0,
      progress: 8,
      image: 'assets/images/exercises/workouts/arm.png',
      exerciseDataList: [
        ExerciseData(
          title: 'Bicep Curls',
          minutes: TextConstants.recliningMinutes,
          progress: 0.0,
          imagePath: ['assets/images/exercises/workouts/bicep-curl.jpg'],
          name: [],
          amount: [],
          video: PathConstants.recliningVideo,
          description: 'Bicep curls are a classic isolation exercise targeting the biceps brachii, the muscle group located on the front of the upper arm. This exercise can be performed with dumbbells, a barbell, or a cable machine.',
          steps: [
            'Stand with feet shoulder-width apart, holding a dumbbell in each hand with arms fully extended at your sides, palms facing forward.',
            'Keeping your upper arms stationary, exhale and curl the weights towards your shoulders by contracting your biceps. Keep your elbows close to your torso throughout the movement.',
            'At the top of the movement, squeeze your biceps for a moment to maximize muscle engagement.',
            'Inhale and slowly lower the weights back down to the starting position, maintaining control.',
            'Exhale as you curl the weights up and inhale as you lower them down.',
          ],
        ),
        ExerciseData(
          title: 'Tricep Dips',
          minutes: TextConstants.cowPoseMinutes,
          progress: 0.0,
          imagePath: ['assets/images/exercises/workouts/tricep-dips.jpg'],
          name: [],
          amount: [],
          video: PathConstants.cowPoseVideo,
          description: 'Tricep dips are a compound exercise that primarily targets the triceps, but also engage the shoulders and chest as secondary muscles. This exercise can be performed using parallel bars, a dip station, or a sturdy bench.',
          steps: [
            'Position yourself between parallel bars, supporting your body with straight arms.',
            'Lower your body by bending your elbows until your upper arms are parallel to the ground.',
            'Exhale and push through your palms to straighten your arms, returning to the starting position.',
          ],
        ),
        ExerciseData(
          title: 'Hammer Curls',
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0.0,
          imagePath: ['assets/images/exercises/workouts/hammer-curls-bicep.jpg'],
          name: [],
          amount: [],
          video: PathConstants.warriorIIVideo,
          description: 'Cable hammer curls are an effective variation of traditional bicep curls that target the biceps brachii, brachialis, and brachioradialis muscles. By using a cable machine with a straight bar attachment, you maintain constant tension on the muscles throughout the entire range of motion, which can lead to enhanced muscle activation and growth.',
          steps: [
            'Stand facing a cable machine with a straight bar attachment at the lowest position. Grab the bar with a neutral grip (palms facing each other).',
            'Exhale and bend your elbows, curling the bar toward your shoulders while keeping your upper arms stationary.',
            'At the top of the movement, squeeze your biceps and forearm muscles.',
            'Inhale and slowly lower the bar back down to the starting position, maintaining control and resisting the weight stack\'s pull.',
          ],
        ),
        ExerciseData(
          title: 'Tricep Pushdown',
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0.0,
          imagePath: ['assets/images/exercises/workouts/tricep-rope-pushdown-800.jpg'],
          name: [],
          amount: [],
          video: PathConstants.warriorIIVideo,
          description: 'Tricep rope pushdowns are an effective isolation exercise targeting the triceps. This exercise is performed using a cable machine with a rope attachment.',
          steps: [
            'Attach a rope handle to the high pulley of a cable machine. Stand facing the machine and grab the rope with an overhand grip, palms facing down.',
            'Keep your elbows close to your sides and exhale as you push the rope downwards until your arms are fully extended.',
            'At the bottom of the movement, squeeze your triceps to maximize muscle engagement.',
            'Inhale and slowly allow the rope to return to the starting position, controlling the weight.',
            'Exhale as you push the rope down and inhale as you allow it to return.',
          ],
        ),
      ],
    ),
    WorkoutData(
      title: TextConstants.cardioTitle,
      exercices: TextConstants.cardioExercises,
      minutes: TextConstants.cardioMinutes,
      currentProgress: 0,
      progress: 8,
      image: 'assets/images/exercises/workouts/cardio.jpg',
      exerciseDataList: [
        ExerciseData(
          title: 'Cycling',
          minutes: TextConstants.recliningMinutes,
          progress: 0.0,
          imagePath: ['assets/images/exercises/workouts/cycling.png'],
          name: [],
          amount: [],
          video: PathConstants.recliningVideo,
          description: 'Cycling is an excellent low-impact cardio exercise that can be performed indoors on a stationary bike or outdoors. It strengthens the lower body and improves cardiovascular endurance.',
          steps: [
            'Adjust your bike to fit your body, ensuring proper seat height and handlebar position.',
            'Start with a 5-minute warm-up at a moderate pace to get your muscles ready.',
            'Pedal at a steady pace, maintaining a comfortable cadence (70-90 RPM). For interval training, alternate between high-intensity sprints and moderate recovery periods.',
            'End with a 5-minute cool-down at a slow pace, followed by stretching to reduce muscle tightness.',
          ],
        ),
        ExerciseData(
          title: 'Running Intervals',
          minutes: TextConstants.cowPoseMinutes,
          progress: 0.0,
          imagePath: ['assets/images/exercises/workouts/run.jpg'],
          name: [],
          amount: [],
          video: PathConstants.cowPoseVideo,
          description: 'Running intervals involve alternating between high-speed running and periods of walking or slow jogging. This method enhances cardiovascular fitness and improves speed and endurance.',
          steps: [
            'Start with a 5-minute jog or brisk walk to warm up your muscles.',
            'Run at your maximum speed for 30 seconds to 1 minute.',
            'Follow with 1 to 2 minutes of walking or slow jogging to recover.',
            'Continue alternating between sprinting and recovery for a total of 20-30 minutes. Finish with a 5-minute cool-down jog or walk and stretching.',
          ],
        ),
        ExerciseData(
          title: 'Rowing',
          minutes: TextConstants.warriorPoseMinutes,
          progress: 0.0,
          imagePath: ['assets/images/exercises/workouts/rowing.png'],
          name: [],
          amount: [],
          video: PathConstants.warriorIIVideo,
          description: 'Rowing is a low-impact cardio exercise that works both the upper and lower body. It\'s great for building endurance and muscular strength while being gentle on the joints.',
          steps: [
            'Sit on the rowing machine, secure your feet in the foot straps, and grasp the handle with both hands.',
            'Push off with your legs while pulling the handle towards your chest, keeping your back straight and core engaged.',
            'Extend your arms and slide forward, bending your knees to return to the starting position.',
            'Maintain a steady pace, focusing on smooth, powerful strokes. Breathe rhythmically, exhaling during the drive phase and inhaling during the recovery.',
          ],
        ),
      ],
    )
  ];

  static final List<WorkoutData> homeWorkouts = [
    WorkoutData(
        title: TextConstants.cardioTitle,
        exercices: TextConstants.cardioExercises,
        minutes: TextConstants.cardioMinutes,
        currentProgress: 10,
        progress: 15,
        image: PathConstants.cardio,
        exerciseDataList: [
          ExerciseData(
            title: TextConstants.reclining,
            minutes: TextConstants.recliningMinutes,
            progress: 1,
            imagePath: ['assets/icons/home/logoB.png'],
            name: [],
            amount: [],
            video: PathConstants.recliningVideo,
            description: TextConstants.warriorDescription,
            steps: [
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
              TextConstants.warriorStep1,
              TextConstants.warriorStep2,
            ],
          ),
          ExerciseData(
            title: TextConstants.cowPose,
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.3,
            imagePath: ['assets/icons/home/logoB.png'],
            name: [],
            amount: [],
            video: PathConstants.cowPoseVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            title: TextConstants.warriorPose,
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.99,
            imagePath: ['assets/icons/home/logoB.png'],
            name: [],
            amount: [],
            video: PathConstants.warriorIIVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
        ]),
    WorkoutData(
        title: TextConstants.armsTitle,
        exercices: TextConstants.armsExercises,
        minutes: TextConstants.armsMinutes,
        currentProgress: 1,
        progress: 20,
        image: PathConstants.cardio,
        exerciseDataList: [
          ExerciseData(
            title: TextConstants.reclining,
            minutes: TextConstants.recliningMinutes,
            progress: 0.1,
            imagePath: ['assets/icons/home/logoB.png'],
            name: [],
            amount: [],
            video: PathConstants.recliningVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            title: TextConstants.cowPose,
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.1,
            imagePath: ['assets/icons/home/logoB.png'],
            name: [],
            amount: [],
            video: PathConstants.cowPoseVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
          ExerciseData(
            title: TextConstants.warriorPose,
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.0,
            imagePath: ['assets/icons/home/logoB.png'],
            name: [],
            amount: [],
            video: PathConstants.warriorIIVideo,
            description: TextConstants.warriorDescription,
            steps: [TextConstants.warriorStep1, TextConstants.warriorStep2],
          ),
        ]),
  ];

  // Receitas
  static final List<WorkoutData> recipes = [
    WorkoutData(
        title: 'Breakfast',
        exercices: TextConstants.Breakfast1,
        minutes: TextConstants.Breakfast2,
        currentProgress: 10,
        progress: 16,
        image: 'assets/images/receitas/breakfast.jpg',
        exerciseDataList: [
          ExerciseData(
            title: 'Greek Yogurt',
            minutes: TextConstants.recliningMinutes,
            progress: 0.5,
            imagePath: [
              'assets/images/receitas/greek-yogurt.jpg',
              'assets/images/receitas/iogurte.png',
              'assets/images/receitas/berries.png',
              'assets/images/receitas/granola.png',
              'assets/images/receitas/honey.png',
            ],
            name: [
              "Yogurt",
              "Berries",
              "Granola",
              "Honey"
            ],
            amount: [
              "200 gr",
              "10 pieces",
              "2 spoonfuls",
              "1 spoonful"
            ],
            video: 'assets/images/receitas/greek-yogurt.jpg',
            description: 'Greek yogurt is an excellent source of protein, which helps keep you full and satisfied. Berries provide antioxidants, vitamins, and fiber, while granola adds crunch and additional fiber. This parfait is a balanced meal that can be customized to your taste and nutritional needs.',
            steps: [
              'In a glass or bowl, start with a layer of Greek yogurt.',
              'Top the yogurt with a layer of mixed berries.',
              'Sprinkle a handful of granola over the berries.',
              'Repeat the layers as desired, ending with a yogurt layer.',
              'Drizzle a bit of honey or maple syrup on top if you prefer a sweeter taste.',
              'Sprinkle chia seeds on top for added texture and nutrition.',
            ],
          ),
          ExerciseData(
            title: "Avocado Toast with Egg",
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.3,
            imagePath: [
              'assets/images/receitas/toast.jpg',
              'assets/images/receitas/bread.png',
              'assets/images/receitas/avocado.png',
              'assets/images/receitas/egg.png'

            ],
            name: [
              "bread",
              "avocado",
              "eggs",
            ],
            amount: [
              "2 slices",
              "1 unit",
              "2 units",
            ],
            video: 'assets/images/receitas/toast.jpg',
            description: "This breakfast combines complex carbohydrates, healthy fats, and protein. The whole grain bread provides sustained energy, while the avocado offers heart-healthy fats. The poached eggs add high-quality protein, making this a nutrient-dense and satisfying meal.",
            steps: [
              'Toast the bread slices until they are golden and crispy.',
              'In a bowl, mash the ripe avocado with a fork. Mix in the lemon juice, salt, and pepper to taste.',
              'Evenly spread the mashed avocado on the toasted bread slices.',
              'Poach the eggs in simmering water with a dash of vinegar to help set the whites. Cook until the whites are set, but the yolk remains runny, about 3-4 minutes.',
              'Place a poached egg on each slice of avocado toast.',
              'Sprinkle with red pepper flakes if desired, and serve immediately.',
            ],
          ),
          ExerciseData(
            title: "Smoothie Bowl",
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.99,
            imagePath: [
              'assets/images/receitas/smothie.png',
              'assets/images/receitas/berries.png',
              'assets/images/receitas/banana.png',
              'assets/images/receitas/milk.png',
              'assets/images/receitas/nuts.png',
            ],
            name: [
              "berries",
              "banana",
              "milk",
              "nuts",
            ],
            amount: [
              "1 cup",
              "1 piece",
              "1/2 cup",
              "a sprinkle",
            ],
            video: 'assets/images/receitas/smothie.png',
            description: "",
            steps: [
              'In a blender, combine the frozen berries, banana, spinach or kale, and almond milk. Blend until smooth and thick. If the mixture is too thick, add a bit more almond milk.',
              'Pour the smoothie into a bowl. The consistency should be thick enough to hold the toppings.',
              'Arrange your choice of sliced fruits, nuts, seeds, coconut flakes, and granola on top of the smoothie. Be creative with your toppings for added texture and flavor.',
            ],
          ),
        ]),
    WorkoutData(
        title: TextConstants.Lunch,
        exercices: TextConstants.Lunch1,
        minutes: TextConstants.Lunch2,
        currentProgress: 1,
        progress: 20,
        image: 'assets/images/receitas/lunch.jpg',
        exerciseDataList: [
          ExerciseData(
            title: "Quinoa Salad",
            minutes: TextConstants.recliningMinutes,
            progress: 0.1,
            imagePath: [
              'assets/images/receitas/quinoa_salad.jpeg',
              'assets/images/receitas/quinoa.png',
              'assets/images/receitas/chickpeas.png',
              'assets/images/receitas/tomato.png',
              'assets/images/receitas/cucumber.png',
              'assets/images/receitas/cheese.png',
            ],
            name: [
              "quinoa",
              "chickpeas",
              "tomato",
              "cucumber",
              "cheese",
            ],
            amount: [
              "1 cup",
              "1 can",
              "1 cup",
              "1 piece",
              "100 gr",
            ],
            video: 'assets/images/receitas/quinoa_salad.jpeg',
            description: 'This quinoa salad is rich in plant-based protein, fiber, and a variety of vitamins and minerals. It\'s a refreshing and light lunch that provides sustained energy throughout the afternoon.',
            steps: [
              'Rinse quinoa under cold water and cook according to package instructions. Allow to cool.',
              'Dice the cucumber and halve the cherry tomatoes.',
              'In a large bowl, combine the cooled quinoa, chickpeas, cherry tomatoes, cucumber, and feta cheese if using.',
              'In a small bowl, whisk together olive oil and lemon juice. Pour over the quinoa salad and toss to coat evenly.',
              'Divide the quinoa salad into lunch containers. Keep it chilled until ready to eat.',
            ],
          ),
          ExerciseData(
            title: "Turkey Wrap",
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.1,
            imagePath: [
              'assets/images/receitas/turkey.jpg',
              'assets/images/receitas/tortilla.png',
              'assets/images/receitas/turkey.png',
              'assets/images/receitas/avocado.png',
              'assets/images/receitas/greens.png',
              'assets/images/receitas/hummus.png',
            ],
            name: [
              "tortilla",
              "turkey",
              "avocado",
              "greens",
              "hummus",
            ],
            amount: [
              "2 pieces",
              "4 slices",
              "1 piece",
              "1 cup",
              "2 spoonfuls",
            ],
            video: 'assets/images/receitas/turkey.jpg',
            description: 'These turkey and veggie wraps are a balanced meal with lean protein, healthy fats, and plenty of vegetables. They are easy to prepare and pack, making them a convenient and nutritious lunch option.',
            steps: [
              'Thinly slice the red bell pepper and avocado.',
              'Place the whole grain tortillas on a clean surface.',
              'Spread a thin layer of hummus over each tortilla.',
              'Place two slices of roasted turkey breast on each tortilla.',
              'Layer mixed greens, sliced red bell pepper, and avocado on top of the turkey.',
              'Fold in the sides of the tortilla and then roll it up tightly from the bottom. Slice in half if desired.',
              'Wrap each tortilla in parchment paper or place in a lunch container.',
            ],
          ),
        ]),
    WorkoutData(
        title: TextConstants.Snacks,
        exercices: TextConstants.Snacks1,
        minutes: TextConstants.Snacks2,
        currentProgress: 12,
        progress: 14,
        image: 'assets/images/receitas/snacks.jpg',
        exerciseDataList: [
          ExerciseData(
            title: 'Apple with Almond Butter',
            minutes: TextConstants.recliningMinutes,
            progress: 0.99,
            imagePath: [
              'assets/images/receitas/appleButter.jpg',
              'assets/images/receitas/apple.png',
              'assets/images/receitas/butter.png',
              'assets/images/receitas/honey.png',
              'assets/images/receitas/granola.png',
            ],
            name: [
              "apple",
              "nut butter",
              "honey",
              "granola",
            ],
            amount: [
              "1 piece",
              "2 tablespoon",
              "1 teaspoon",
              "1 tablespoon",
            ],
            video: 'assets/images/receitas/appleButter.jpg',
            description: 'This snack is a great combination of fiber, healthy fats, and a touch of sweetness. It provides a good energy boost and is very easy to prepare.',
            steps: [
              'Wash the apple thoroughly and cut it into thin slices.',
              'Spread a small amount of almond butter on each apple slice.',
              'Drizzle with honey and sprinkle with granola if desired.',
              'Arrange the apple slices on a plate or pack them in a container for a quick and easy snack.',
            ],
          ),
          ExerciseData(
            title: 'Cereal Bar',
            minutes: TextConstants.cowPoseMinutes,
            progress: 0.6,
            imagePath: [
              'assets/images/receitas/bar.jpeg',
              'assets/images/receitas/oats.png',
              'assets/images/receitas/honey.png',
              'assets/images/receitas/butter.png',
              'assets/images/receitas/nuts.png',
              'assets/images/receitas/d_fruit.png',
            ],
            name: [
              "oats",
              "honey",
              "nut butter",
              "nuts",
              "fruits",
            ],
            amount: [
              "1 cup",
              "1 spoon",
              "2 spoons",
              "1/2 cup",
              "1 cup",
            ],
            video: 'assets/images/receitas/bar.jpeg',
            description: 'These homemade cereal bars are packed with whole grains, healthy fats, and natural sweetness. They are perfect for a quick, on-the-go snack and can be stored in an airtight container for up to a week.',
            steps: [
              'Line an 8x8 inch baking dish with parchment paper, leaving some overhang to easily lift the bars out later.',
              'In a large bowl, combine the rolled oats, mixed nuts and seeds, and dried fruit.',
              'In a small saucepan over low heat, combine the honey or maple syrup, nut butter, and vanilla extract. Stir until the mixture is smooth and well combined.',
              'Pour the warm wet mixture over the dry ingredients. Stir until everything is well coated and evenly mixed.',
              'Transfer the mixture to the prepared baking dish. Use a spatula or your hands to press it down firmly and evenly.',
              'Place the dish in the refrigerator for at least 2 hours, or until the mixture is firm and set.',
              'Once set, lift the mixture out of the dish using the parchment paper overhang and place it on a cutting board. Cut into bars of your desired size.',
            ],
          ),
          ExerciseData(
            title: 'Sticks with Hummus',
            minutes: TextConstants.warriorPoseMinutes,
            progress: 0.8,
            imagePath: [
              'assets/images/receitas/sticks.jpeg',
              'assets/images/receitas/carrot.png',
              'assets/images/receitas/cucumber.png',
              'assets/images/receitas/hummus.png',
            ],
            name: [
              'Carrots',
              'Cucumber',
              'Hummus',
            ],
            amount: [
              '2 pieces',
              '2 pieces',
              '1/2 cup',
            ],
            video: 'assets/images/receitas/sticks.jpeg',
            description: 'This snack is simple, nutritious, and crunchy. The combination of fresh vegetables with protein-rich hummus makes it a satisfying and healthy choice.',
            steps: [
              'Wash and peel the carrots. Cut both the carrots and cucumber into sticks.',
              'Place the hummus in a small bowl or container.',
              'Arrange the carrot and cucumber sticks on a plate or in a container with the hummus for dipping.',
            ],
          ),
        ]),
    WorkoutData(
      title: TextConstants.Dinner,
      exercices: TextConstants.Dinner1,
      minutes: TextConstants.Dinner2,
      currentProgress: 0,
      progress: 8,
      image: 'assets/images/receitas/dinner.jpg',
      exerciseDataList: [
        ExerciseData(
          title: 'Salmon with Asparagus',
          minutes: TextConstants.recliningMinutes,
          progress: 0.0,
          imagePath: [
            'assets/images/receitas/bakedSalmon.jpg',
            'assets/images/receitas/salmon.png',
            'assets/images/receitas/aspargus.png',
            'assets/images/receitas/lemon.png'
          ],
          name: [
            'salmon',
            'asparagus',
            'lemon',
          ],
          amount: [
            '1 fillet',
            '3 units',
            '1/2 piece',
          ],
          video: 'assets/images/receitas/bakedSalmon.jpg',
          description: 'This dinner is a light yet satisfying option packed with protein, healthy fats, and vitamins. The baked salmon is rich in omega-3 fatty acids, and the asparagus provides fiber and essential nutrients.',
          steps: [
            'Preheat your oven to 400°F (200°C).',
            'Line a baking sheet with parchment paper or aluminum foil.',
            'Place the salmon fillets on the baking sheet. Drizzle with olive oil, and sprinkle with salt, pepper, and garlic powder if using.',
            'Arrange the asparagus around the salmon on the baking sheet. Drizzle with olive oil, and sprinkle with salt and pepper.',
            'Place lemon slices over the salmon and asparagus.',
            'Bake in the preheated oven for 15-20 minutes, or until the salmon is cooked through and the asparagus is tender.',
            'Transfer to plates and serve immediately.',
          ],
        ),
        ExerciseData(
          title: 'Chicken and Avocado Salad',
          minutes: TextConstants.cowPoseMinutes,
          progress: 0.0,
          imagePath: [
            'assets/images/receitas/chickenSalad.jpg',
            'assets/images/receitas/frango.png',
            'assets/images/receitas/avocado.png',
            'assets/images/receitas/greens.png',
            'assets/images/receitas/tomato.png',
          ],
          name: [
            'Chicken',
            'Avocado',
            'Greens',
            'Tomato',
          ],
          amount: [
            '2 breasts',
            '1 unit',
            '2 cups',
            '1/4 cup',
          ],
          video: 'assets/images/receitas/chickenSalad.jpg',
          description: 'This chicken and avocado salad is a fresh and hearty meal. The chicken provides lean protein, while the avocado adds healthy fats. The mixed greens and cherry tomatoes offer a variety of vitamins and antioxidants.',
          steps: [
            'Season the chicken breasts with salt and pepper. Heat 1 tablespoon of olive oil in a skillet over medium heat. Cook the chicken for about 6-7 minutes per side, or until fully cooked through. Let it rest for a few minutes, then slice.',
            'In a large bowl, combine the mixed greens and cherry tomatoes.',
            'Add the diced avocado to the salad.',
            'In a small bowl, whisk together the remaining olive oil and balsamic vinegar. Drizzle over the salad and toss to combine.',
            'Top the salad with the sliced chicken.',
            'Divide into portions and serve immediately.',
          ],
        ),
      ],
    ),
    WorkoutData(
      title: TextConstants.Desserts,
      exercices: TextConstants.Desserts1,
      minutes: TextConstants.Desserts2,
      currentProgress: 0,
      progress: 8,
      image: 'assets/images/receitas/desserts.png',
      exerciseDataList: [
        ExerciseData(
          title: 'Baked Apples with Cinnamon',
          minutes: TextConstants.recliningMinutes,
          progress: 0.0,
          imagePath: [
            'assets/images/receitas/baked.jpg',
            'assets/images/receitas/apple.png',
            'assets/images/receitas/honey.png',
            'assets/images/receitas/cinnamon.png',
            'assets/images/receitas/nuts.png',
          ],
          name: [
            'Apple',
            'Honey',
            'Cinnamon',
            'Nuts',
          ],
          amount: [
            '2 pieces',
            '2 tablespoon',
            '1 teaspoon',
            '1/4 cup',
          ],
          video: 'assets/images/receitas/baked.jpg',
          description: 'Baked apples with cinnamon are a warm and comforting dessert. They are naturally sweetened and provide a good source of fiber and healthy fats from the nuts.',
          steps: [
            'Preheat your oven to 350°F (175°C).',
            'Core the apples and place them in a baking dish.',
            'In a small bowl, combine honey (or maple syrup), ground cinnamon, chopped nuts, and coconut oil.',
            'Fill the cavities of the apples with the nut mixture.',
            'Cover the baking dish with foil and bake for 20-25 minutes. Remove the foil and bake for an additional 10-15 minutes, or until the apples are tender.',
            'Let the apples cool slightly before serving.',
          ],
        ),
        ExerciseData(
          title: 'Banana Nice Cream',
          minutes: TextConstants.cowPoseMinutes,
          progress: 0.0,
          imagePath: [
            'assets/images/receitas/nice.jpg',
            'assets/images/receitas/banana.png',
            'assets/images/receitas/butter.png',
            'assets/images/receitas/berries.png',
            'assets/images/receitas/Choco.png',
          ],
          name: [
            'banana',
            'nut butter',
            'berries',
            'chocolate',
          ],
          amount: [
            '2 peices',
            '1 tablespoon',
            '10 pieces',
            '50 gr',
          ],
          video: 'assets/images/receitas/nice.jpg',
          description: 'Banana nice cream is a delicious and guilt-free dessert made entirely from fruit. It\'s creamy, naturally sweet, and can be enjoyed as a healthy alternative to traditional ice cream.',
          steps: [
            'Slice the bananas and freeze them in a single layer on a baking sheet for at least 2 hours or overnight.',
            'Place the frozen banana slices in a food processor or blender. Blend until smooth and creamy, scraping down the sides as needed.',
            'Add almond butter and vanilla extract to the blended bananas. Blend again until well combined.',
            'Scoop the banana nice cream into bowls. Top with fresh berries or dark chocolate shavings if desired. Serve immediately.',
          ],
        ),
      ],
    )
  ];

  // Reminder
  static List<String> reminderDays = [
    TextConstants.everyday,
    TextConstants.monday_friday,
    TextConstants.weekends,
    TextConstants.monday,
    TextConstants.tuesday,
    TextConstants.wednesday,
    TextConstants.thursday,
    TextConstants.friday,
    TextConstants.saturday,
    TextConstants.sunday,
  ];
}
